global_vars:
  - name: _time
    type: date
    params:
        format: "%H:%M:%S"

  - name: _date
    type: date
    params:
        format: "%Y年%m月%d日"
      
      
matches:
  # >>>>>>>>>>>>>> datetime >>>>>>>>>>>>>>
  # date
  - trigger: ":date"
    replace: "{{_date}}"
          
  # time
  - trigger: ":time"
    replace: "{{_time}}"
    
  # datetime
  - trigger: ":dtime"
    replace: "{{_date}} {{_time}}"
  # <<<<<<<<<<<<<< datetime <<<<<<<<<<<<<<
    
    
    
  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/